### ISSUE TITLE
How to change duration animation show and close slide 

### ISSUE THREAD

**Issue by chuvanhoang888** [FlutterWay/bottom_sheet_scaffold#1]
I did not find the property to change the slide effect of the silde, do you have a workaround for this. Thank.

**Comment by worldwidee** [comment]
Hi
new version has animationDuration property in DraggableBottomSheet

**Comment by worldwidee** [comment]
if you have any other questions, our discord channel is https://discord.gg/gkVfnrQg

**Comment by chuvanhoang888** [comment]
> if you have any other questions, our discord channel is https://discord.gg/gkVfnrQg

That's awesome, thank you for adding it
